apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cp-customer-record.fullname" . }}
  labels:
    {{- include "cp-customer-record.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cp-customer-record.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cp-customer-record.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cp-customer-record.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP      
          env:
            - name: "AzureADB2COptions__TenantName"
              value: "{{ .Values.azureADB2COptionsTenantName }}"
            - name: "AzureADB2COptions__TenantId"
              value: "{{ .Values.azureADB2COptionsTenantId }}"
            - name: "AzureADB2COptions__URI"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com/{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com/oauth2/v2.0/authorize"
            - name: "AzureADB2COptions__Authority"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com/tfp/{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com/B2C_1A_SIGNIN/oauth2/v2.0"
            - name: "MongoDbOptions__DbName"
              value: "{{ .Values.dbCPCustomerRecord }}"
            - name: "MongoDbOptions__ConnectionString"
              value: "{{ .Values.mongoDbConnectionString }}"
            - name: "RabbitMqSettings__HostName"
              value: "{{ .Values.rabbitmqHost }}"
            - name: "RabbitMqSettings__UserName"
              value: "{{ .Values.rabbitmqUser }}"
            - name: "RabbitMqSettings__Password"
              value: {{ .Values.rabbitmqPassword | quote }}
            - name: "RabbitMqSettings__VirtualHost"
              value: "{{ .Values.rabbitmqVHost }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
