apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "strapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "strapi.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "strapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.namespace }}-strapi-storage-claim
          persistentVolumeClaim:
            claimName: {{ .Values.namespace }}-strapi-storage-claim
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          terminationMessagePath: "/tmp/my-log"
          volumeMounts:
            - name: {{ .Values.namespace }}-strapi-storage-claim
              mountPath: /srv/app
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_NAME
              value: {{ .Values.dbStrapi }}
            - name: DATABASE_HOST
              value: {{ .Values.dbHost }}
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: {{ .Values.dbUser }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.dbPassword }}
            - name: DATABASE_SSL
              value: "true"
            - name: SENDGRID_API_KEY
              value: {{ .Values.sendGridAccountSettingsApiKey }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 1337
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 1337
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
