apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-rebuilderui
data:
  config.js: |
    window._config_ = {
      AppUrl: '{{ .Values.reBuilderUIPublicURL }}',
      API_DOMAIN: '{{ .Values.reBuilderApiPublicURL }}'
    };