apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cp-file-storage.fullname" . }}
  labels:
    {{- include "cp-file-storage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cp-file-storage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cp-file-storage.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cp-file-storage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: "AzureAd__Domain"
              value: "{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com"
            - name: "AzureAd__Instance"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com"
            - name: "AzureAd__ClientId"
              value: "{{ .Values.azureADB2COptionsApplicationIdFileStorage }}"
            - name: "AzureAd__ClientSecret"
              value: {{ .Values.azureADB2COptionsClientSecretFileStorage | quote }}
            - name: "PoliciesAPISettings__URI"
              value: "http://insurance-api.{{ .Values.commonNamespace }}.svc.cluster.local"              
            - name: "PoliciesAPISettings__ClientId"
              value: "{{ .Values.cpFileStoragePoliciesAPISettingsClientId }}" 
            - name: "PoliciesAPISettings__ClientSecret"
              value: {{ .Values.cpFileStoragePoliciesAPISettingsClientSecret | quote }}
            - name: "BlobStorageSettings__AccountName"
              value: "null"
            - name: "BlobStorageSettings__AccountKey"
              value: "null"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
