apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cp-auth-api.fullname" . }}
  labels:
    {{- include "cp-auth-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cp-auth-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cp-auth-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cp-auth-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- if ne (.Values.cpEmailMethodSettingViaComms | toString ) "true" }}
            - name: "sendGridAccountSettingsApiKey"
              value: {{ .Values.sendGridAccountSettingsApiKey | quote }}
            {{- end }}
            {{- if eq (.Values.cpEmailMethodSettingViaComms | toString ) "true" }}
            - name: "EmailAPIOptions__URI"
              value: "http://cp-email-service.{{ .Values.cpNamespace }}.svc.cluster.local"
            {{- end }}
            - name: "ConnectionStrings__RedisConnectionString"
              value: "redis-master.{{ .Values.cpNamespace }}.svc:6379,password=secretpassword,abortConnect=false"
            - name: "RabbitMqSettings__Hostname"
              value: "{{ .Values.rabbitmqHost }}"
            - name: "RabbitMqSettings__UserName"
              value: "{{ .Values.rabbitmqUser }}"
            - name: "RabbitMqSettings__Password"
              value: "{{ .Values.rabbitmqPassword }}"
            - name: "RabbitMqSettings__VirtualHost"
              value: "{{ .Values.rabbitmqVHost }}"
            # AzureADB2COptions__AzureBaseLinkTemplate potentially not used
            - name: AzureADB2COptions__AzureBaseLinkTemplate
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com/{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com/oauth2/v2.0/authorize"
            - name: "AzureADB2COptions__TenantName"
              value: "{{ .Values.azureADB2COptionsTenantName }}"
            - name: "AzureADB2COptions__ApplicationId"
              value: "{{ .Values.azureADB2COptionsApplicationIdAuthService }}"
            - name: "AzureADB2COptions__TenantId"
              value: "{{ .Values.azureADB2COptionsTenantId }}"
            - name: "AzureADB2COptions__ClientSecret"
              value: {{ .Values.azureADB2COptionsClientSecretAuthService | quote }}
            - name: "AzureADB2COptions__URI"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com/{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com/oauth2/v2.0/authorize"
            - name: "AzureADB2COptions__SignUpRedirectionLink"
              value: "{{ .Values.webUrlCPUI }}"
            - name: "AzureADB2COptions__Authority"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com/tfp/{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com/B2C_1A_SIGNIN/oauth2/v2.0"
            - name: "AzureAd__Domain"
              value: "{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com"
            - name: "AzureAd__Instance"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.b2clogin.com"
            - name: "AzureAd__TenantId"
              value: "{{ .Values.azureADB2COptionsTenantId }}"
            - name: "AzureAd__ClientId"
              value: "{{ .Values.azureADB2COptionsApplicationIdAuthService }}"
            - name: "AzureAd__ClientSecret"
              value: {{ .Values.azureADB2COptionsClientSecretAuthService | quote }}
            - name: "CustomerAPIOptions__URI"
              value: "http://cp-customer-info-proxy.{{ .Values.cpNamespace }}.svc.cluster.local"
            - name: "CustomerAPIOptions__Scopes__0"
              value: "https://{{ .Values.azureADB2COptionsTenantName }}.onmicrosoft.com/{{ .Values.azureADB2COptionsApplicationIdCustomerInformationProxy }}/.default"
            - name: "PhoneVerificationServiceOptions__URI"
              value: "http://cp-phone-verification.{{ .Values.cpNamespace }}.svc.cluster.local"
            - name: "CustomerAPIOptions__TimeoutInMilliseconds"
              value: "{{ .Values.cpCustomerInfoProxyAPIOptionsTimeoutInMilliseconds }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
