apiVersion: v1
kind: Service
metadata:
  name: {{ include "comms-strapi.fullname" . }}
  labels:
    {{- include "comms-strapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1337
      protocol: TCP
      name: "http"
  selector:
    {{- include "comms-strapi.selectorLabels" . | nindent 4 }}
