apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-reexecutionui
data:
  config.js: |
    window._config_ = {
      AppUrl: '{{ .Values.reExecutionUIPublicURL }}',
      API_DOMAIN: '{{ .Values.reExecutionApiPublicURL }}'
    };